### ISSUE TITLE
extension.ts after extension activation #buildFormatCommand() should implement the correct defaults

### ISSUE THREAD

**Issue by iansan5653** [iansan5653/vscode-format-python-docstrings#28]
Unit test is failing on `master`:
```
Expected values to be strictly equal: + actual - expected  + Promise { +   <pending> + } - 'docformatter "path" --wrap-summaries 79 --wrap-descriptions 72'
```
Stack trace:
```
AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ Promise {
+   <pending>
+ }
- 'docformatter "path" --wrap-summaries 79 --wrap-descriptions 72'
	at Context.<anonymous> (out/test/extension.test.js:203:24)
	at processImmediate (internal/timers.js:439:21)
```

**Comment by iansan5653** [comment]
Looks like I forgot to await the `Promise` result here.
